apiVersion: apps/v1
kind: Deployment
metadata:
  name: discounts
  namespace: restauranty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: discounts
  template:
    metadata:
      labels:
        app: discounts
        role: discounts
        service-type: application
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - t2.small
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service-type
                  operator: In
                  values:
                  - application
              topologyKey: kubernetes.io/hostname
      containers:
      - name: discounts
        image: sfischer46/restauranty-discounts:v1
        ports:
        - containerPort: 3002
        env:
        - name: PORT
          value: "3002"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: restauranty-env
              key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: discounts
  namespace: restauranty
spec:
  selector:
    app: discounts
  ports:
  - port: 3002
    targetPort: 3002
    protocol: TCP
  type: ClusterIP
