version: "3.8"

services:
  auth:
    container_name: auth
    build: ./backend/auth
    ports:
      - "${AUTH_PORT}:3001"
    env_file:
      - .env
    environment:
      - PORT=3001
      - SECRET=${SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}

  discounts:
    container_name: discounts
    build: ./backend/discounts
    ports:
      - "${DISCOUNTS_PORT}:3002"
    env_file:
      - .env
    environment:
      - PORT=3002
      - SECRET=${SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}

  items:
    container_name: items
    build: ./backend/items
    ports:
      - "${ITEMS_PORT}:3003"
    env_file:
      - .env
    environment:
      - PORT=3003
      - SECRET=${SECRET}
      - MONGODB_URI=${MONGODB_URI}
      - CLOUD_NAME=${CLOUD_NAME}
      - CLOUD_API_KEY=${CLOUD_API_KEY}
      - CLOUD_API_SECRET=${CLOUD_API_SECRET}

  frontend:
    container_name: frontend
    build:
      context: ./client
      args:
        REACT_APP_API_URL: http://34.220.9.168  # change to your actual API URL
    ports:
      - "${FRONTEND_PORT}:80"

  haproxy:
    container_name: haproxy
    image: haproxy:latest
    ports:
      - "80:80"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - auth
      - discounts
      - items
      - frontend
