apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: restauranty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        role: auth
        service-type: application
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: node.kubernetes.io/instance-type
                operator: In
                values:
                - t2.small
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - weight: 100
            podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: service-type
                  operator: In
                  values:
                  - application
              topologyKey: kubernetes.io/hostname
      containers:
      - name: auth
        image: sfischer46/restauranty-auth:v1
        ports:
        - containerPort: 3001
        env:
        - name: PORT
          value: "3001"
        - name: SECRET
          valueFrom:
            secretKeyRef:
              name: restauranty-env
              key: SECRET
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: restauranty-env
              key: MONGODB_URI
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: restauranty
spec:
  selector:
    app: auth
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
