apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
  namespace: restauranty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
        role: backend
    spec:
      containers:
      - name: auth
        image: sfischer46/restauranty-auth:v1
        ports:
        - containerPort: 3001
        env:
          - name: SECRET
            valueFrom:
              secretKeyRef:
                name: restauranty-env
                key: SECRET
          - name: MONGODB_URI
            valueFrom:
              secretKeyRef:
                name: restauranty-env
                key: MONGODB_URI
          - name: CLOUD_NAME
            valueFrom:
              secretKeyRef:
                name: restauranty-env
                key: CLOUD_NAME
          - name: CLOUD_API_KEY
            valueFrom:
              secretKeyRef:
                name: restauranty-env
                key: CLOUD_API_KEY
          - name: CLOUD_API_SECRET
            valueFrom:
              secretKeyRef:
                name: restauranty-env
                key: CLOUD_API_SECRET
          - name: REACT_APP_SERVER_URL
            valueFrom:
              secretKeyRef:
                name: restauranty-env
                key: REACT_APP_SERVER_URL
---
apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: restauranty
spec:
  selector:
    app: auth
  ports:
  - port: 3001
    targetPort: 3001
    protocol: TCP
  type: ClusterIP
