apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: restauranty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        role: frontend
    spec:
      nodeSelector:
        role: frontend
      containers:
      - name: frontend
        image: sfischer46/restauranty-frontend:v1
        ports:
        - containerPort: 3000
        env:
        - name: REACT_APP_SERVER_URL
          value: "https://sebsrestaurant.diogohack.shop"
        - name: AUTH_SERVICE_URL
          value: "http://auth:3001"
        - name: DISCOUNTS_SERVICE_URL
          value: "http://discounts:3002"
        - name: ITEMS_SERVICE_URL
          value: "http://items:3003"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: restauranty
spec:
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: ClusterIP
