apiVersion: apps/v1
kind: Deployment
metadata:
  name: items
  namespace: restauranty
spec:
  replicas: 1
  selector:
    matchLabels:
      app: items
  template:
    metadata:
      labels:
        app: items
        role: items
        service-type: application
    spec:
      nodeSelector:
        service: items
      containers:
      - name: items
        image: sfischer46/restauranty-items:v1
        ports:
        - containerPort: 3003
        env:
        - name: PORT
          value: "3003"
        - name: MONGODB_URI
          valueFrom:
            secretKeyRef:
              name: restauranty-env
              key: MONGODB_URI
        - name: CLOUD_NAME
          valueFrom:
            secretKeyRef:
              name: restauranty-env
              key: CLOUD_NAME
        - name: CLOUD_API_KEY
          valueFrom:
            secretKeyRef:
              name: restauranty-env
              key: CLOUD_API_KEY
        - name: CLOUD_API_SECRET
          valueFrom:
            secretKeyRef:
              name: restauranty-env
              key: CLOUD_API_SECRET
---
apiVersion: v1
kind: Service
metadata:
  name: items
  labels:
    app: items
  namespace: restauranty
spec:
  selector:
    app: items
  ports:
  - name: http
    port: 3003
    targetPort: 3003
    protocol: TCP
  type: ClusterIP
