apiVersion: v1
kind: Service
metadata:
  name: auth
  namespace: restauranty
  labels:
    app: auth
spec:
  selector:
    app: auth
  ports:
    - name: http          # name added for ServiceMonitor
      port: 3001
      targetPort: 3001
  type: ClusterIP