apiVersion: v1
kind: Service
metadata:
  name: discounts
  namespace: restauranty
  labels:
    app: discounts
spec:
  selector:
    app: discounts
  ports:
    - name: http          # name added for ServiceMonitor
      port: 3002
      targetPort: 3002
  type: ClusterIP