apiVersion: v1
kind: Service
metadata:
  name: items
  namespace: restauranty
  labels:
    app: items
spec:
  selector:
    app: items
  ports:
    - name: http          # name added for ServiceMonitor
      port: 3003
      targetPort: 3003
  type: ClusterIP