name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}
  LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        run: echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      # -----------------------------
      # Build & push backend services
      # -----------------------------
      - name: Build and push auth service
        run: |
          docker build -t $DOCKERHUB_USERNAME/restauranty-auth:latest ./backend/auth
          docker push $DOCKERHUB_USERNAME/restauranty-auth:latest

      - name: Build and push discounts service
        run: |
          docker build -t $DOCKERHUB_USERNAME/restauranty-discounts:latest ./backend/discounts
          docker push $DOCKERHUB_USERNAME/restauranty-discounts:latest

      - name: Build and push items service
        run: |
          docker build -t $DOCKERHUB_USERNAME/restauranty-items:latest ./backend/items
          docker push $DOCKERHUB_USERNAME/restauranty-items:latest

      # -----------------------------
      # Build & push frontend
      # -----------------------------
      - name: Build and push frontend
        run: |
          docker build -t $DOCKERHUB_USERNAME/restauranty-frontend:latest ./client
          docker push $DOCKERHUB_USERNAME/restauranty-frontend:latest

      # -----------------------------
      # Deploy to EKS
      # -----------------------------
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.31.0'

      - name: Configure kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > kubeconfig
          export KUBECONFIG=$PWD/kubeconfig

      - name: Deploy applications
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          
          # Deploy regular manifests (non-cert-manager)
          kubectl apply -f k8s/auth/
          kubectl apply -f k8s/discounts/
          kubectl apply -f k8s/items/
          kubectl apply -f k8s/frontend/
          kubectl apply -f k8s/mongo/
          kubectl apply -f k8s/ingress/
          kubectl apply -f k8s/monitoring/
          kubectl apply -f k8s/logging/

      - name: Deploy cert-manager with environment substitution
        env:
          LETSENCRYPT_EMAIL: ${{ secrets.LETSENCRYPT_EMAIL }}
        run: |
          export KUBECONFIG=$PWD/kubeconfig
          
          # Apply cert-manager manifests with environment substitution
          envsubst < k8s/cert-manager/cluster-issuer.yaml | kubectl apply -f -
          envsubst < k8s/cert-manager/letsencrypt-prod.yaml | kubectl apply -f -
          envsubst < k8s/cert-manager/letsencrypt-staging.yaml | kubectl apply -f -
