name: CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Set up DockerHub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # Build & push auth service image
      - name: Build and push auth service Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/restauranty-auth:latest ./backend/auth
          docker push $DOCKERHUB_USERNAME/restauranty-auth:latest

      # Build & push items service image
      - name: Build and push items service Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/restauranty-items:latest ./backend/items
          docker push $DOCKERHUB_USERNAME/restauranty-items:latest

      # Build & push discounts service image
      - name: Build and push discounts service Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/restauranty-discounts:latest ./backend/discounts
          docker push $DOCKERHUB_USERNAME/restauranty-discounts:latest

      # Build & push frontend image
      - name: Build and push frontend Docker image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=${{ env.REACT_APP_API_URL }} \
            -t $DOCKERHUB_USERNAME/restauranty-frontend:latest ./client
          docker push $DOCKERHUB_USERNAME/restauranty-frontend:latest

      # Set up kubeconfig from base64 secret
      - name: Set up kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      # Deploy to EKS
      - name: Deploy to EKS
        run: |
          # Update image tags in deployments
          kubectl set image deployment/auth-deployment auth=$DOCKERHUB_USERNAME/restauranty-auth:latest -n restauranty
          kubectl set image deployment/items-deployment items=$DOCKERHUB_USERNAME/restauranty-items:latest -n restauranty
          kubectl set image deployment/discounts-deployment discounts=$DOCKERHUB_USERNAME/restauranty-discounts:latest -n restauranty
          kubectl set image deployment/frontend-deployment frontend=$DOCKERHUB_USERNAME/restauranty-frontend:latest -n restauranty
          
          # Wait for rollout to complete
          kubectl rollout status deployment/auth-deployment -n restauranty
          kubectl rollout status deployment/items-deployment -n restauranty
          kubectl rollout status deployment/discounts-deployment -n restauranty
          kubectl rollout status deployment/frontend-deployment -n restauranty
