name: CI/CD

on:
  push:
    branches:
      - main

env:
  AWS_REGION: us-west-2
  DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
  REACT_APP_API_URL: ${{ secrets.REACT_APP_API_URL }}

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS CLI
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      # Set up DockerHub login
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ env.DOCKERHUB_USERNAME }}
          password: ${{ env.DOCKERHUB_TOKEN }}

      # Build & push backend image
      - name: Build and push backend Docker image
        run: |
          docker build -t $DOCKERHUB_USERNAME/restauranty-backend:latest ./backend
          docker push $DOCKERHUB_USERNAME/restauranty-backend:latest

      # Build & push frontend image
      - name: Build and push frontend Docker image
        run: |
          docker build \
            --build-arg REACT_APP_API_URL=${{ env.REACT_APP_API_URL }} \
            -t $DOCKERHUB_USERNAME/restauranty-frontend:latest ./client
          docker push $DOCKERHUB_USERNAME/restauranty-frontend:latest

      # Set up kubeconfig from base64 secret
      - name: Set up kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 --decode > $HOME/.kube/config

      # Deploy to EKS
      - name: Deploy to EKS
        run: |
          kubectl set image deployment/backend-deployment backend=$DOCKERHUB_USERNAME/restauranty-backend:latest -n restauranty
          kubectl set image deployment/frontend-deployment frontend=$DOCKERHUB_USERNAME/restauranty-frontend:latest -n restauranty
          kubectl rollout status deployment/backend-deployment -n restauranty
          kubectl rollout status deployment/frontend-deployment -n restauranty
